### ISSUE TITLE
How long can bot be running without logging out? 

### ISSUE THREAD

**Issue by kubapilch** [fbchat-dev/fbchat#361]
Please mark it as question. 

How long I can leave my bot logged in and running on VPS? I know that you can’t tell me exact number of hours/days but I want to know if I have to log out, once per day for example, to not get banned by Facebook. 

Should I use some method to log out and log in once per X or maybe log in with cookies to make it more like real person, instead of a bot that is running 24/7?

**Comment by kapi2289** [comment]
I'm running few bots 24/7 and I don't have any problems with it.

**Comment by szymonszl** [comment]
I'm running a bot pretty much 24/7, restarting it only when I'm upgrading it or something goes wrong. I'm storing and logging in from cookies, so I guess that for FB it looks kind of like a browser tab with Messenger I keep running on my computer with my real account? Anyway, no problems yet.
I've lost an account to logging in/out all the time before though.

**Comment by Demindiro** [comment]
My bot keeps running indefinitely until the account I use gets blocked (4 accounts and still counting...). It usually gets blocked while developing, so it probably indeed has something to do with logging in.

If you really need to keep it running, you could make a script that restarts the bot if you are logged out (or modify the bot itself) and switch between a list of accounts, if that is an option.

**Comment by MikSDigital** [comment]
Now FB blocked fresh account immediately ... I am not able to login either

**Comment by aspiringguru** [comment]
came here looking for info on FB blocking accounts. Just had a new dummy account blocked. after multiple logins during development. Not surprised FB is escalating their detecting and blocking. curious what strategies others are using to minimise this problem. 

are there other methods with less problems? I've previously used selenium for automated logins and actions on other systems. will try the methods shown below.

https://stackoverflow.com/questions/45635190/logging-facebook-using-selenium

**Comment by kubapilch** [comment]
I have experimented with a couple of strategies and the most successful one was making the account as real as possible.

I mean, set a profile photo, background photo, fill all data about the account like school, work etc. I have also commented couple of posts and followed 40+ pages, I have added as many friends as possible and licked lot of posts. Also you should wait like a day or two after creating the account, in this time use it as your primary account and try to comment and like as much as possible.

**Comment by kapi2289** [comment]
My account was named Bot Bot , and now I need to change the name to some real one, or Facebook will block my account in a few days.

**Comment by aspiringguru** [comment]
ok. that all makes sense.

**Comment by madsmtm** [comment]
I've found that the most important thing is that you have a phone number. I've gotten my primary account blocked several times after I moved my phone number to a test account, but this test account hasn't yet been blocked. But it's not really an exact science... 🤔

**Comment by szymonszl** [comment]
Hm, the account I use for a bot is not at all made to look legit, the name is an obvious misspelling of my name (think Saymon instead of Simon), the profile pic is of a drawing of a robot, it has ***no phone number attached*** and it sends a lot of repetitive messages (it's responding to commands sent by friends). It's pretty obvious it's a bot if you look at it.

It's still up somehow. Still, even if it gets blocked I can make a new one and just switch the credentials in the script.

Things I think were important with it staying up:
- Lots of messages exchanged
- Lots of friends
- Not a lot of logging in, storing cookies
- It being active from the start and staying active, so it doesn't suspiciously go from being unused to overused.

Your mileage may vary.

**Comment by aspiringguru** [comment]
Thanks szymonszl, if you can share examples of how you manage sessions it would be appreciated.

* Not a lot of logging in, storing cookies
I looked this up, annoyed I missed this obvious better method.
https://fbchat.readthedocs.io/en/master/intro.html#logging-in

from fbchat import Client
from fbchat.models import *
client = Client("<email>", "<password>")
session_cookies = client.getSession()
client.setSession(session_cookies)

#do stuff.
#sleep 
client.setSession(session_cookies)
#do more stuff

I'm still thinking about how to use this, maybe login with password, store the session cookies as above, do stuff, sleep for (say) one hour (?) set session cookies then resume doing stuff.

need to think about what exceptions to catch and how to handle them. 

also need to think about how to do dev and testing off line without having to restart the app regularly.


I'm a bit cautious about over investing in a project with this codebase since I'm half expecting FB to tighten on bots outside their official api. Went to a presentation by a senior FB engineer recently and their logging is very advanced, to the extent I'm quite certain any activity outside their app is obvious. The logging distinguishes between the thousands of different phone models quite accurately for example.

**Comment by szymonszl** [comment]
I just did it pretty much the documentation way, here's an excerpt from the code of my bot:

```
cookies = pickle.load(open('cookies.p','rb'))
client = BotClient(login, password, session_cookies=cookies, logging_level=30)
session = clientobj.getSession()
pickle.dump(session,open('cookies.p','wb'))
client.listen()
```

This is the only part of the code when cookies are accesed. The bot is `listen`-ing all the time, which propably keeps the cookies up-to-date and stops them from expiring (at least that's what it seems like, all I care about is that it works ¯\\\_(ツ)_/¯). I'm not sure what to do if you're not using `listen` though.

**Comment by miguelwon** [comment]
I had the same problem. Then I started to use `session_cookies` to re-login and didn't have any more issues.
